### ISSUE TITLE
SourceMap - Path is missing

### ISSUE THREAD

**Issue by schlaup** [andreypopp/typescript-loader#10]
Hello,

first, thanks for this loader! Well done!

I tried to integrate it into my project and found out that the path is missing from the source maps.

Lets assume that I have a file under

app/model/somedata.ts

After setting the option to generate the source map and opening Chrome devtools, I find the source under the root of "webpack://" instead of "webpack://app/model".

Peter

**Comment by jonjaques** [comment]
What does your `entry` setting look like? I believe by default webpack will do some heuristics to determine the base directory for your app. So you could maybe set the base to `./`and see what happens?

**Comment by schlaup** [comment]
The "entry" setting points outside of the app folder.

To be more clear:

I am testing your loader with a react starter from:

https://github.com/webpack/react-starter

"entry" points to "config/app.jsx".

I changed the starter: I added your "typescript-loader", a TypeScript file to the "SomePage" folder, referenced it from a page and set "devtool: "#source-map"

I do not believe that it is related to the settings, because the source maps that are generated for the JSX files of the project are correct. (i.e. "webpack://app/SomePage/index.jsx")

In Chrome you see:

> webpack://app/SomePage/index.jsx
> webpack://somedata.ts

although "somedata.ts" is in the same "SomePage" folder in my project.

Btw, I also set

> output.devtoolModuleFilenameTemplate: "[resource-path]"

because Webstorm does not like "webpack://" - however, with or without this option it does not work.

**Comment by schlaup** [comment]
Here is another observation that might lead to the problem or solution:

There was / is an issue with WebPack and Webstorm:

https://github.com/webpack/webpack/issues/238

The proposed solution works by removing "devtools" and instead using:

> new webpack.SourceMapDevToolPlugin(
>           '[file].map', null,
>            "[absolute-resource-path]", "[absolute-resource-path]")

I tried this and saw that "jsx-loader" generates source maps and your "typescript-loader" does not with this config.

Maybe there is a connection? Maybe your loader needs to use the "webpack.SourceMapDevToolPlugin" and this would take care of setting the correct path in the source map?

(Now there is the "output.devtoolModuleFilenameTemplate" option and it seems the above workaround is not required anymore.)

_As I said: This is only an observation and I do not have an understanding of the webpack code base. So I am just wondering if the two issues are related._

**Comment by schlaup** [comment]
I saw the same issue with ts-loader and found a solution:

https://github.com/jbrantly/ts-loader/issues/8

You can probably use a similiar code (four lines) to fix this loader as well.

**Comment by schlaup** [comment]
Just to let you know that there is an additional problem with redundant sourceMappingURLs that Typescript places directly in the output Javascript file.

The fix is an additional line of code. Please see the ts-loader issue for the solution:

https://github.com/jbrantly/ts-loader/issues/8
