### ISSUE TITLE
Simpler implementation possible?

### ISSUE THREAD

**Issue by jbrantly** [andreypopp/typescript-loader#2]
Howdy. I tried using this a couple days ago but immediately ran into issues with the way imports are found and resolved. For example, ambient interfaces like `require('react/addons')` resulted in the loader literally trying to load that module which didn't exist. I figured there had to be an interface exposed that would walk the dependency tree, so I went digging and eventually came up with this:

https://gist.github.com/jbrantly/7a374d27f329a651fbec

That is a completely functioning loader in 58 files which offloads most of the work to TypeScript. The key piece is `typescript.createProgram()` and `program.getSourceFiles()` which causes TypeScript to walk the dependency tree starting from one file. Each file that is found is added to the language service so that it can be emitted if the loader ever asks for it. I believe a simplistic approach like this is the way to go.

There are a couple of additional notes:
1. Almost all file I/O is happening within TypeScript which does not have an async interface. Therefore everything is sync. This could potentially have some performance downsides but it does make the code significantly less complex.
2. We don't need to do anything special to the files like adding References to the top as near as I can tell. I'm unsure why the webpack runtime is added to the top of every file.
3. As near as I can tell the code is not making use of versioning which can allow for quick recompiles if just a single file changes, for example.

Are you open to some of the changes above? I wanted to check first before putting the work in on a PR. I believe implementing these changes would gut quite a bit of the existing codebase.

**Comment by jgoz** [comment]
I'm all for a simpler implementation, but there is something else to consider:

Webpack allows dependencies of non-source files (e.g. CSS, text resources, arbitrary loaders, etc.) to be referenced from source files, but typescript only deals with module dependencies (ts or .d.ts). Offloading resolution entirely to typescript will make it impossible to support non-source dependencies.

Personally, I'd rather have a pure implementation that only supports modules resolvable by typescript, but this may alienate some webpack users. I handled this in my loader with a hacky transform that looked for any untranslatable `/// resource` declarations and converted them directly to `require` statements in the resulting JS, but I'm not really sure how this impacts webpack's internal dependency graph.

One other thing to consider is sourcemap support, which I don't think either implementation supports at this point. @andreypopp's allows enabling the option, but I couldn't see where the resulting sourcemap was supplied to webpack.

**Comment by jbrantly** [comment]
re: non-source files, that is a good point that I had not considered. Off the top of my head I can see two options there:
1. Support `import css = require('!style!css!./style.css')`. Along with named external module declarations it seems to work in my super quick test. I'm not a webpack expert but I think that might be all that's required since TS will turn that import into `var css = require('!style!css!./style.css')` which should then get picked up by the webpack pipeline. I'll have to test this further when I can get a chance unless someone else beats me to it.
2. Come up with some other special syntax that doesn't break TS and allows us to preprocess it into requires, similar to your `/// resource` mechanism.

Regarding sourcemaps, +1

**Comment by jgoz** [comment]
With option 1, if TS translates the import/require statement for CSS without generating additional errors, then (I believe) it should work fine on webpack's end.

**Comment by jbrantly** [comment]
Eh, I couldn't wait. Option #1 above does work, at least in my limited test. Zero change to the TS loader. As long as what comes out of TS has "var whatever = require('whatever')", then webpack will pick those up. The trick is in making sure TS doesn't bomb on your import statement, and that your import statement doesn't get removed due to non-use. Not bombing can be handled via external module declarations, and simply referencing the imported variable makes sure it doesn't get removed.

**Comment by jgoz** [comment]
> Not bombing can be handled via external module declarations, and simply referencing the imported variable makes sure it doesn't get removed.

So it isn't possible to do this?

``` ts
// in bar.ts
require("!style!css!./foo.css");
```

That might be confusing to a lot of people, especially if they're familiar with webpack.

**Comment by jbrantly** [comment]
Sorry, you're absolutely right. You can do it (I just modified my test slightly, it works). I just put `declare var require: (string) => void;` in a declarations file and `require("!style!css!./foo.css");` in my TS file. That is probably a saner default way to handle it, although both work and neither require the TS loader to do anything, so it's really up to the end user.

**Comment by jgoz** [comment]
Oh! I think that's what @andreypopp is doing with `webpack-runtime.d.ts`.

Seems like a good solution.

**Comment by jbrantly** [comment]
You're right, that does answer that. However, I would contend that it would be better to leave it out of the loader. You're going to be blowing errors in your IDE if you don't reference that file yourself anyways. Instead I would recommend shipping with that file and including instructions on how to reference it yourself if you need it. Then your IDE is happy and TS is still happy.

Edit: Also by not including it you make sure you don't step on anyone's toes that might want to do something else with a globally declared "require" function.

**Comment by jgoz** [comment]
> However, I would contend that it would be better to leave it out of the loader. You're going to be blowing errors in your IDE if you don't reference that file yourself anyways. Instead I would recommend shipping with that file and including instructions on how to reference it yourself if you need it. Then your IDE is happy and TS is still happy.

That's a really good point and seems like a great compromise for people who want full support of webpack features vs those who just want/need a pure TS loader. 

:+1: 

Edit: also, avoiding direct modification of TS inputs/JS outputs will preserve sourcemap line accuracy, which is necessary for debugging.

**Comment by andreypopp** [comment]
Regarding `webpack-runtime.d.ts` — I still want to have it injected automatically but I understand that this will mangle source maps so I think there's another way to do that (via lang service API).

**Comment by andreypopp** [comment]
Regarding the original issue — I don't understand what doesn't work... in the example if I modify

```
import React = require('react')
```

to

```
import React = require('react/addons')
```

it still works.

I prefer to handle module resolution through Webpack (and in fact I'm impressed by the quality of TypeScript compiler API which allows that) because that would allow interoperability with the numerous WebPack plugins which provide custom resolution logic.

**Comment by andreypopp** [comment]
@jbrantly so as I understand the only principal difference in your approach and mine is that I walk AST by myself and resolve references via Webpack and you use `typescript.createProgram()` which employs TypeScript compiler to do AST walking and I/O to fetch sources.

**Comment by jbrantly** [comment]
> so as I understand the only principal difference in your approach

@andreypopp I believe you've hit the nail on the head. In my mind it has two advantages.
1. Less room for issues/differences between a normal tsc compilation.
2. Much less code.

**Comment by jbrantly** [comment]
> Regarding the original issue — I don't understand what doesn't work... in the example if I modify

Honestly I'm not sure. I just tried it again. I downloaded the zip file from the repo, extracted it, and ran:

```
npm install
cd example
webpack

Module build failed: Error: Cannot resolve module 'react' in C:\dev\typescript-loader-master\example
```

(I'm on Windows, not sure if that makes a difference.)

Do you by chance have react installed globally?

> because that would allow interoperability with the numerous WebPack plugins which provide custom resolution logic

I'm new to webpack. Could you give an example of what you mean by this? Are you saying that someone should be able to use `NormalModuleReplacementPlugin` to swap out `import MyClass = require('./myClass')` with `import MyClass = require('./myOtherClass')`?

**Comment by andreypopp** [comment]
Sorry, example doesn't come with `package.json`, I'll fix it but in the meantime you should install react/style-loader/css-loader by hand.

> Are you saying that someone should be able to use NormalModuleReplacementPlugin to swap out import MyClass = require('./myClass') with import MyClass = require('./myOtherClass')?

Yes, it should be possible though I didn't try it yet.

**Comment by jgoz** [comment]
@jbrantly, @andreypopp 

> in the meantime you should install react/style-loader/css-loader by hand.

This worked for me (on Mac OS), before & after changing to `require('react/addons')`. I can try from my windows machine at work tomorrow. React is not globally installed on either machine.

**Comment by andreypopp** [comment]
Ok, I don't prepend webpack runtime reference anymore and added support for source maps. It works flawlessly!

**Comment by jbrantly** [comment]
I was able to get it working. There is currently an issue on Windows with path normalization, but after fixing that the example seems to be working and I can't purposefully break it. I'll have to try my other project again tomorrow (the one that was originally having issues with `typescript-webpack-plugin`). Perhaps it was just a bug prior to the rewrite?

I'll also submit a PR tomorrow to fix the Windows issue.

**Comment by andreypopp** [comment]
@jbrantly yeah, you said you tried it few days ago but I pushed it on github just yesterday...

**Comment by jgoz** [comment]
Confirmed working on my end. I'll test on Windows tomorrow too.

Nice work!

**Comment by andreypopp** [comment]
@jgoz added you as a collaborator on the repo

**Comment by jbrantly** [comment]
Apologies, I assumed the new version kept the same file resolving logic as `typescript-webpack-plugin` and that the issue lay in that architecture and not so much the implementation details, but I was probably wrong.

In any case, agreed, nice work on source maps.

**Comment by jgoz** [comment]
https://github.com/andreypopp/typescript-loader/pull/1#issuecomment-70609756

**Comment by jbrantly** [comment]
With #3 I can successfully compile the example app out-of-the-box. With the discussion regarding other plugins changing the resolve path I can see the argument for keeping the current architecture instead of relying on TS to resolve the dependency graph. I think it's slightly more brittle and certainly more complex but there is a reason for the complexity so... I would be good with closing this issue.

**Comment by andreypopp** [comment]
@jbrantly thanks for #3, as for #2, let's keep it this way (resolution via WebPack) at least before we discover serious issues with it...
