### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by andreypopp** [andreypopp/typescript-loader#4]
I wasn't able to implement it via `require.ensure`:

```
require.ensure(['./module'], function(require) {
  import module = require('./module');
});
```

Because TypeScript can't parse it:

```
/Users/andreypopp/Workspace/typescript-loader/example/index.ts (28, 7) Statement expected.
```

Are `import` statements only allowed at top level?

**Comment by jgoz** [comment]
This may be helpful: http://www.typescriptlang.org/Handbook#modules-optional-module-loading-and-other-advanced-loading-scenarios

**Comment by andreypopp** [comment]
@jgoz thanks! fbb255d fixes this
