### ISSUE TITLE
How to gain a reference to an internal module?

### ISSUE THREAD

**Issue by jonjaques** [andreypopp/typescript-loader#6]
Hello, 

I'm having some trouble figuring out how to work with TypeScript's [internal](https://github.com/Microsoft/TypeScript/wiki/Modules#multi-file-internal-modules) modules. 

From what I can tell, you're supposed to just reference them using the `///` syntax and with a normal tsc compile, they would be within the global or at least module level namespace. 

I've done some debugging and found that typescript-loader is indeed picking up the reference and reading the file, but I believe what's happening is the file isn't actually exporting anything and therefore webpack doesn't have reason to include it in the build.
I've pushed a branch illustrating the issue [here](https://github.com/jonjaques/typescript-loader/tree/internal-modules).

Likewise, if you try to `import` it like an external module, TypeScript will yell at you for doing so. However, as I was writing this out it occurred to me to try writing `export = {moduleName}`, along with an `import` - and it worked exactly as expected. 

The problem still remains though of how not to modify vendor files? What would the webpack way of handling this be (and also what is feasible from the loader's point of view)?

Personally, I dislike the idea of internal modules altogether and would prefer to handle everything as an external module. That seems like most node/webpack like.

**Comment by jonjaques** [comment]
@andreypopp or @jgoz what are your thoughts on this? I'm going to have time tonight and would like to tackle this. 

I'm thinking I want to detect internal modules and automatically export them to make them compatible with webpack. The other approach I can think off would be to be to assign them to the `global` namespace but that seems hacky. 

Yet another idea would be to somehow leverage the [export loader](http://webpack.github.io/docs/shimming-modules.html#exposing) or the [provide plugin](http://webpack.github.io/docs/list-of-plugins.html#provideplugin), however I'm unsure or how to access these from the loader context.

**Comment by andreypopp** [comment]
I'm not sure if we should make typescript-loader so smart so it automatically lifts non-CommonJS compatible modules to compatible ones (using export loader or not). Probably the best idea is to leave that task up to the user (to configure export loader or provide plugin for libraries which don't export anything). That would be also consistent with JS story.

**Comment by jonjaques** [comment]
Yeah, it might be doing a little bit too much. It seems possible to infer an internal module through the AST, but hard to know what to do since it probably varies with context. As I'm looking into webpack more it seems like a plugin would be the best for this use case. 

For now the workaround would be to reference it like so:

```
/// <reference path="internal.ts" />
var foo: typeof foomodule = require('exports?foomodule!./internal');
```

This adds quite a bit of overhead though, 1.2s to my tiny codebase for just this one file.

**Comment by andreypopp** [comment]
Do you mean that `exports-loader` results in 1.2s? Is this case (internal modules) common in TypeScript ecosystem?

**Comment by jonjaques** [comment]
Yeah, with `exports-loader` - however I may have been mistaken, adding a few more files + exports didn't increase compile time noticeably. 

To be honest I'm not sure about internal modules, I'm just getting into TS and one of the first projects I looked at was [typescript-collections](https://github.com/basarat/typescript-collections) (which is defined in that style). That being said, it seems like the focus going forward is ES6 and external modules definitely seem like the way to go for me. 

Perhaps I can just throw a note in the readme?

**Comment by andreypopp** [comment]
@jonjaques right, I think documenting the best practices of using `typescript-loader` is the way to go here.

**Comment by jgoz** [comment]
@jonjaques Do internal modules work with the loader if they only define interfaces? I.e. If they provide type information but no actual implementations?

This seems like the only semi-reasonable use of internal modules to me: as a `.d.ts` equivalent for pure TS code. But I'd still structure my own code as external modules.

I agree that we should document which TS features are not supported.

**Comment by jonjaques** [comment]
Yup, TypeScript sees them just fine - the problem lies with webpack and files being wrapped in closures. Submitted a PR with clarification.

**Comment by andreypopp** [comment]
Closing as #8 is merged.
