### ISSUE TITLE
Support Custom typescript compiler

### ISSUE THREAD

**Issue by fdecampredon** [andreypopp/typescript-loader#9]
It could be useful if that module let you choose the compiler implementation used (we could for example use https://github.com/fdecampredon/jsx-typescript :D)

**Comment by jonjaques** [comment]
I would like this feature too, however typescript-loader makes heavy use of the new language services API from 1.4 so it would need to be compatible with that. One simple change would be to make typescript a peer-dependency, so you could always choose which TS version you're using. However I'm not sure if you could completely swap out the tsx-typescript dependency. 

So in our `package.json` do:

```
{
  "name": "typescript-loader",
  "peerDependencies": {
    "typescript": ">=1.4.0"
  }
}
```

And then in your app:

```
{
  "name": "myapp",
  "devDependencies": {
    "typescript": "https://github.com/fdecampredon/jsx-typescript.git#commitish"
  }
}
```

However! I don't know if that would work - somebody feel free to correct me.

**Comment by fdecampredon** [comment]
I'm not so sure since the 2 project has different package name need to give it a try

**Comment by andreypopp** [comment]
I added support for this via `typescriptCompiler` loader option:

```
    loaders: [
      {
        test: /\.ts$/,
        loader: 'typescript-loader?typescriptCompiler=jsx-typescript'
      }
    ]
```

But you need to install `jsx-compiler` yourself for this to work.

**Comment by fdecampredon** [comment]
:+1:
